# Get all brands
GET http://localhost:3000/api/brands/



###
# Get brand by id
GET http://localhost:3000/api/brands/609a29dc6542d153f86da754
 

###
# Create brand
POST http://localhost:3000/api/brands/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MGEzZjJkOGZkODQ2MDNlODM2NGI4YTYiLCJpYXQiOjE2MjE1MTM5NzR9.C7L2StI5sadC1kEZE0usbePBjpqlNIwe0xlvI8JbuE8

{
    "name": "Điện thoại iPhone 12 64GB",
    "category": "609a202d1100534046b7efb3",
    "logo": null
}


###
# Delete brand by id
DELETE http://localhost:3000/api/brands/609a28c55d6c30515c8e4c70
 

###
# Update brand by id
PUT http://localhost:3000/api/brands/609a29dc6542d153f86da754
Content-Type: application/json

{
    "name": "Laptop Acer Aspire A315 56 34AY i3 1005G1/4GB/512GB/Win10 (NX.HS5SV.007)",
    "category": "609a226e0fba9b43c1d9c04b",
    "price": "12990000",
    "image": "img1.jpg",
    "content": "Acer Aspire được làm từ chất liệu nhựa, có độ hoàn thiện cao, đường nét tỉ mỉ tạo nên tổng thể máy sang trọng, thời trang. Chiếc máy này có độ dày 19.9 mm và cân nặng 1.7 kg đủ mỏng nhẹ để bạn thoải mái đem theo đi học, đi làm hằng ngày."
}
     

### 
GET http://localhost:3000/api/test